Feature/feature mint
python-college/nft-marketplace-web pull request #7
Opened 2024-11-10 09:45 UTC by wsppppp

минт коллекций и нфт

2024-11-10 09:56 UTC, kutkovmax requested changes
![image](https://github.com/user-attachments/assets/332d682e-7799-4baa-a8bd-17127c58af92)

2024-11-10 09:56 UTC, kutkovmax commented on nft_marketplace/pages/static/pages/js/mint/mint.js
> +    alert("Royalty должно быть в диапазоне от 0 до 50%");
алёрты?

2024-11-10 09:56 UTC, kutkovmax commented on nft_marketplace/pages/static/pages/js/mint/mint_nft.js
> +      if (response.type === "mint_nft_data_processed" && response.message === "Data successfully received and processed") {
второе условие не нужно

2024-11-10 09:56 UTC, kutkovmax commented on nft_marketplace/pages/static/pages/js/mint/mint.js
> +            alert("Коллекция успешно создана!"); // Всплывающее сообщение
... mint_collection_data_processed означает что данные получены и транзакция отправилась в кошелёк пользователя.

Надо ожидать второе сообщение с типом mint_collection_success +еще обработать отказ пользователя mint_collection_user_rejects.

И второе условие нужно удалить

2024-11-10 10:12 UTC, wsppppp commented on nft_marketplace/pages/static/pages/js/mint/mint_nft.js
> +      if (response.type === "mint_nft_data_processed" && response.message === "Data successfully received and processed") {
ок

2024-11-11 07:35 UTC, kutkovmax approved these changes
ладно, норм

2024-11-11 07:36 UTC, merged